### ISSUE TITLE
Praise and request: solo

### ISSUE THREAD

**Issue by spectromas** [gluethegiant/gtg-rack#1]
First of all, I would like to say thank you for these modules. I have always been monolithic mixer person but the way you have implemented the bus system is very appealing and useful for me. It's great how easy it is to set up some effect sends and complicated routing. 

The only thing I miss immediately is a solo function. I'm not sure how it could be implemented but right click or control click on mute would be cool.

**Comment by gluethegiant** [comment]
I'm glad they are useful for you. And thank you for the suggestion. I hope to roll out some more features soon.

**Comment by gluethegiant** [comment]
The upcoming Road module in 1.0.5 provides audition (solo) for individual mixers or groups. The new on/audition buttons on Road also have click filters for live use.

Any additional solo features would require communication between modules and that would break the modular design principles. Let me know how you like the new Road module. Thank you again for the feedback!

**Comment by gluethegiant** [comment]
Solo (audition) was added across all mixers. Just long press any mixer on button and any mixer that isn't already long pressed will be muted. Normal click any mixer on button to exit audition mode.

You can also audition Bus Depots (and set master Bus Depots to always audition). In addition, the buttons on Road now have the same audition and multi-audition behavior as the mixer buttons.

The features are now in Git and are being moved to the VCV Rack library within the week. Thanks again for your feedback!
