### ISSUE TITLE
Artwork license question

### ISSUE THREAD

**Issue by falkTX** [gluethegiant/gtg-rack#10]
Just a quick question, as I don't see it mentioned anywhere.
The project is licensed under GPL-3.0-or-later, but does that include the graphics too? Or are those supposed to be in a different license?

The readme states:

> The visual designs under the res/ and designs/ directories help to give these modules a unique look and are automatically copyrighted (c) 2019 in some jurisdictions. Try to not copy them too closely.

But these are not license terms.
Is redistribution allowed? Any kind of modification or derivative works? (taking out the copyrighted names of course) Also selling? Reuse in other works?

Thanks!

**Comment by gluethegiant** [comment]
The intent is not to prohibit derivative works, or distribution of the plugin, including sales, as long as those activities are done following the GPL. The intent of those lines is to ask politely to not use the logo, the exact look, on a derivative plugin. I believe there have been discussions about this type of thing by plugin creators who want to maintain a bit of a "brand" with their plugins. However, I haven't followed those discussions closely. If there is a better way to do this, I'm open to suggestions.

**Comment by falkTX** [comment]
I see, so artwork is just on the same license as the code. What you ask is quite valid and reasonable.

So I ask for a small change to make this clear.
In the readme where you state:

> All the code is released to use under the GPL 3 license and above.

Change to:

> The artwork and all the code are released to use under the GPL 3 license and above.

My question came more from the expectation that artwork license is not the same as code license, for how common that situation is. The change above should help clarify it.
Thanks again.

**Comment by gluethegiant** [comment]
Done. Have a great one!
