### ISSUE TITLE
Build needed for MacOS ARM64

### ISSUE THREAD

**Issue by ltackett** [gluethegiant/gtg-rack#14]
These are easily some of my favorite modules for VCV, and I haven’t been able to use them since VCV released the official MacOS ARM64 build. Any chance this is going to be updated in the future?

**Comment by ltackett** [comment]
I’ve just compiled them with the latest Rack SDK (2.4.1) from the [`development`](https://github.com/gluethegiant/gtg-rack/tree/development) branch. It ran clean and added the devices to VCV Rack. Guess I could have done that this whole time… ¯\\\_(ツ)_/¯ 

@gluethegiant I’m not quite sure what the hold up is on getting these awesome devices back into the VCV Library, but I am glad to have them back!

/cc @baconpaul @clandsky @xandramax

**Comment by ltackett** [comment]
Actually, going to keep this issue open until `development` gets merged into `master`

**Comment by gluethegiant** [comment]
Thank you for the bump. I merged them into master. :)

**Comment by gluethegiant** [comment]
Development branch with renaming merged into master branch.

**Comment by baconpaul** [comment]
Great! 

Curious: are you going to submit a version bump to library? If so it will just then work for all of us Mac folks!

**Comment by gluethegiant** [comment]
Submitted. So sorry. I've been working a couple of jobs and didn't realize how much time was passing.

**Comment by baconpaul** [comment]
Please don’t apologize! Maintaining free software is always best efforts! And maintainer burnout is real!

glad they are coming back!
