### ISSUE TITLE
Mixer inputs"(fade in button to fade out" menu

### ISSUE THREAD

**Issue by blackearth2014** [gluethegiant/gtg-rack#5]
If there is time in the future, could we get a sub context menu for the GIG Bus, Mini, School Bus and Metro Buss that will allow you to set fade in/out values for the off/on buttons? I ofter have counter melodies going on in my patches that I like to fade in/out while live recording. I don't want to have to have multiple modules on the screen to do it.

**Comment by gluethegiant** [comment]
Hi Omar,

This feature is in the works. It's not in the next release, but it's planned for the release right after that. Some of the work is already in place.

The plan has been for the on buttons on each of the mixer strips to work like the on button on Bus Depot. You will be able to right click on them to set the fade in and fade out times. There are a few other things that will make this feature elegant and easy to use.

It will be fun to see this enhancement used on one of your songs!

**Comment by blackearth2014** [comment]
Cool Breeze & Thanks.

**Comment by gluethegiant** [comment]
All mixer modules now have fade automation with separate fade in and fade out speeds that you can access through the context menu. The fades are triggered with the on button or CV. In addition, you can bypass any long fades by ctrl clicking the on button.

These features, along with several other including solo (audition modes) across the modules, is in Git now and will be in the VCV Rack library shortly. Thank you again for using the modules and for your feedback. I hope you enjoy the new fade automation as much as I will!

**Comment by blackearth2014** [comment]
Thanks and I will.
Omar Sharif Brown
Blessed House Media
This is your season
