### ISSUE TITLE
Crashes when setting dark theme as default in Linux

### ISSUE THREAD

**Issue by lepidopteralady1781** [gluethegiant/gtg-rack#8]
The following is a gif of what happens, a picture of my system information, and my log.txt file.
![gtg_vcv_crash](https://user-images.githubusercontent.com/26756285/87390118-ca0a4800-c56d-11ea-8f06-4684f6927e51.gif)
![vcv rack help](https://user-images.githubusercontent.com/26756285/87390126-cecefc00-c56d-11ea-8a19-9e19eff0684a.png)
[log.txt](https://github.com/gluethegiant/gtg-rack/files/4916867/log.txt)

**Comment by gluethegiant** [comment]
When setting global defaults, a GlueTheGiant.json file is written in your Rack root directory. For example, [home]/.Rack/GlueTheGiant.json. Make sure Rack can write to that directory. A couple of other plugins will follow similar behaviors (like Impromptu Modular). It's cool that you run Manjaro. That's been my favorite distro for ages.

**Comment by gluethegiant** [comment]
I was able to duplicate the issue after deleting my /.Rack/GlueTheGiant.json file. I'll get a fix released. Thank you for reporting and let me know if there's anything else I can do.

**Comment by gluethegiant** [comment]
The bug was found and fixed. A new version with the fix (v 1.1.2) has been submitted to the VCV Rack Library and should appear in the library soon. Thank you again for calling this to my attention. You're awesome!
