### ISSUE TITLE
Feature Request: Solo toggle

### ISSUE THREAD

**Issue by mpicard** [gluethegiant/gtg-rack#9]
It would be lovely if there was a solo toggle button on either or all of the Gig Bus, the Mini, the School Bus and the Metro City Bus, similar to the one available in https://github.com/cfoulc/cf

**Comment by gluethegiant** [comment]
The on buttons throughout the modules provide intuitive solo. You can even use the buttons to audition send effects and groups (with Road or by auditioning Bus Depots).

To audition a mixer strip (or solo it), simply long press the on/au (audition) button of the module you want to solo. Add to your audition by long pressing the on/au button of another mixer strip. To audition a send effect, long press the on/au button for the send. You can exit the audition by normal clicking any on/au button in addition mode.

Let me know if this helps or if I can answer any other questions.

**Comment by mpicard** [comment]
Oh no I got RTFM'd 😆 thanks @gluethegiant that's amazing news haha
